/*
 * Copyright (c) 2019 Petr Ptáček
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
package cz.komix.temprec.domain;

import com.google.auto.value.AutoValue;

import java.math.BigDecimal;

/**
 * Immutable instance of measurement sample.
 * A {@code Sample} consist of region name
 * and temperature value. Each {@code Sample}
 * represent one temperature measurement.
 *
 * <p>The {@code Sample} class provides getter for
 * region name and temperature value. There is
 * also factory method to create new instance.
 *
 * <p>New instance of {@code Sample} class can be created
 * only by factory method {@link Sample#create(String, BigDecimal)}.
 * The {@code Sample} class is an abstract class.
 * Concrete implementation is generated by
 * Google AutoValue framework. So there is
 * direct access to any public constructor of {@code Sample}.
 *
 * @author Petr Ptáček
 */
@AutoValue
public abstract class Sample {

    /**
     * Return measurement region name.
     *
     * @return  instance of {@link String}.
     *          Never returns <tt>null</tt>.
     */
    public abstract String region();

    /**
     * Return measurement sample temperature.
     *
     * @return  instance of {@link BigDecimal}.
     *          Never returns <tt>null</tt>.
     */
    public abstract BigDecimal temperature();

    /**
     * Create new instance of {@code Sample}.
     *
     * @param region
     *          measurement region name.
     *
     * @param   temperature
     *          measurement temperature.
     *
     * @return  instance of {@link Sample}.
     *          Never returns <tt>null</tt>.
     */
    public static Sample create(String region, BigDecimal temperature) {
        return new AutoValue_Sample(region, temperature);
    }
}
